name: CMake-Build-Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CMake-Build-Test
    runs-on: ubuntu-latest
    container: ngama75/spqlios-ci:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=ON -DWARNING_PARANOID=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: cd ${{github.workspace}}/build; ctest
