name: CMake-Build-Test-Arm64

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    name: CMake-Build-Test-Arm64
    runs-on: self-hosted-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=ON -DWARNING_PARANOID=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        run: cd ${{github.workspace}}/build; ctest
