name: CMake-Build-Test-Darwin

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-darwin:
    name: CMake-Build-Test-Darwin
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Brew
      run: brew install cmake googletest google-benchmark

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=ON -DWARNING_PARANOID=ON -DDEVMODE_INSTALL=ON

    - name: Build
      run: cmake --build build

    - name: Test
      run: cd build; ctest
    
    - name: Package
      if: github.event_name != 'pull_request'
      env: 
        CI_CREDS: ${{ secrets.CICREDS }}
      run: ./scripts/ci-pkg create

